spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/meowpay
spring.datasource.username=meowpay
spring.datasource.password=meowpay

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
